# Generated by Django 5.0.6 on 2024-06-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_rename_disponibilidade_disponibilidadec'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('sala', models.CharField(max_length=4)),
                ('data', models.CharField(max_length=10)),
            ],
        ),
    ]
