# Generated by Django 5.0.6 on 2024-05-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_disponibilidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='disponibilidade',
            new_name='disponibilidadeC',
        ),
    ]
