# Generated by Django 5.0.6 on 2024-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadec',
            name='foto_sala',
            field=models.ImageField(upload_to='Foto_Sala/'),
        ),
    ]
