# Generated by Django 5.0.6 on 2024-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_remove_disponibilidadec_foto_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadec',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
